import { withAuth } from 'next-auth/middleware';

export default withAuth({
  pages: { signIn: '/login' },
});

export const config = {
  matcher: [
    '/dashboard/:path*',
    '/trips/:path*',
    '/clients/:path*',
    '/vehicles/:path*',
    '/drivers/:path*',
    '/carriers/:path*',
    '/analytics/:path*',
    '/fuel/:path*',
    '/maintenance/:path*',
    '/expiry/:path*',
    '/driver-analytics/:path*',
    '/reports/:path*',
    '/statistics/:path*',
    '/calendar/:path*',
    '/debts/:path*',
    '/documents/:path*',
    '/routes/:path*',
    '/settings/:path*',
    '/api/trips/:path*',
    '/api/clients/:path*',
    '/api/vehicles/:path*',
    '/api/drivers/:path*',
    '/api/carriers/:path*',
    '/api/fuel/:path*',
    '/api/maintenance/:path*',
    '/api/document-expiry/:path*',
    '/api/tire-sets/:path*',
    '/api/driver-analytics/:path*',
    '/api/reports/:path*',
    '/api/statistics/:path*',
    '/api/calendar/:path*',
    '/api/debts/:path*',
    '/api/documents/:path*',
    '/api/route-templates/:path*',
    '/api/settings/:path*',
    '/api/templates/:path*',
    '/api/upload/:path*',
    '/api/vehicles/:path*',
    '/api/exchange-rates/:path*',
  ],
};
