export {
  buildStoragePath,
  buildTripAttachmentDownloadUrl,
  createUploadTarget,
  createUploadTarget as createLocalUploadTarget,
  deleteStoredFile,
  enrichTripAttachmentDownload,
  ensureStorageStructure,
  ensureStorageStructure as ensureLocalStorageStructure,
  getStoredFileSizeBytes,
  isLegacyS3StoragePath,
  isLocalStoragePath,
  isUploadsStoragePath,
  localFileAbsolutePath,
  normalizeStorageCategory,
  normalizeStorageCategory as normalizeCategory,
  readStoredAttachmentFile,
  resolveAttachmentDownloadUrl,
  saveBufferToStorage,
  saveBufferToStorage as saveBufferToLocalStorage,
  verifyStoredAttachmentReadable,
  type StorageCategory,
  type StorageCategory as LocalStorageCategory,
} from '@/lib/attachment-service';
